### ISSUE TITLE
`FakeProcesses` is not compatible with Python 3.7

### ISSUE THREAD

**Issue by jugmac00** [testing-cabal/systemfixtures#10]
Python 3.7 introduced the `text` parameter for `subprocess.run`.

https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module

```
________________________________________________________ TestGetHostArchitecture.test_returns_dpkg_architecture ________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/jugmac00/Projects/lpcraft/lpcraft/tests/test_utils.py", line 81, in test_returns_dpkg_architecture
    self.assertEqual("ppc64el", get_host_architecture())
  File "/home/jugmac00/Projects/lpcraft/lpcraft/utils.py", line 44, in get_host_architecture
    return subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/jugmac00/Projects/lpcraft/.tox/coverage/lib/python3.8/site-packages/systemfixtures/processes/fixture.py", line 42, in __call__
    return super(FakeProcesses, self).__call__(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'text'
```

**Comment by jugmac00** [comment]
It is an upstream issue in `fixtures` 

https://github.com/testing-cabal/fixtures/issues/53

**Comment by jelmer** [comment]
@jugmac00 can we close this now the upstream issue in fixtures has been fixed?

**Comment by jugmac00** [comment]
Thanks for the ping!
