### ISSUE TITLE
shutil.copytree to an overlayed dir fails under Python 3.8

### ISSUE THREAD

**Issue by nessita** [testing-cabal/systemfixtures#8]
When copying a tree to an overlayed dir, I get the following exception casued by `_is_fake_path` not handling DirEntry params:

```python
    shutil.copytree(CHARM_DIR, self.charm_dir)
  File "/usr/lib/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 496, in _copytree
    copy_function(srcobj, dstname)
  File "/usr/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "/home/nessita/canonical/franky/env/lib/python3.8/site-packages/systemfixtures/_overlay.py", line 23, in _new_value
    if self.condition(*args, **kwargs):
  File "/home/nessita/canonical/franky/env/lib/python3.8/site-packages/systemfixtures/filesystem.py", line 146, in _is_fake_path_or_fd
    return self._is_fake_path(path)
  File "/home/nessita/canonical/franky/env/lib/python3.8/site-packages/systemfixtures/filesystem.py", line 133, in _is_fake_path
    if path.startswith(prefix):
AttributeError: 'posix.DirEntry' object has no attribute 'startswith'
```

A possible fix would be something like this:

```python
    129             if isinstance(path, os.DirEntry):
    130                 path = path.name
```

**Comment by nessita** [comment]
To reproduce:
```python
import shutil
import systemfixtures

fs = systemfixtures.FakeFilesystem()
fs.setUp()
fs.add('/dest')

shutil.copytree('/usr/lib/apt', '/dest')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 496, in _copytree
    copy_function(srcobj, dstname)
  File "/usr/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "/home/nessita/canonical/franky/env/lib/python3.8/site-packages/systemfixtures/_overlay.py", line 23, in _new_value
    if self.condition(*args, **kwargs):
  File "/home/nessita/canonical/franky/env/lib/python3.8/site-packages/systemfixtures/filesystem.py", line 146, in _is_fake_path_or_fd
    return self._is_fake_path(path)
  File "/home/nessita/canonical/franky/env/lib/python3.8/site-packages/systemfixtures/filesystem.py", line 133, in _is_fake_path
    if path.startswith(prefix):
AttributeError: 'posix.DirEntry' object has no attribute 'startswith'
```
